name: dungeon of doom ci

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'      
        distribution: 'temurin' 
        cache: maven            

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: dungeonofdoom

    # Step 4: Run unit tests
    - name: Run tests
      run: mvn test
      working-directory: dungeonofdoom
